version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - ls -lrt
      - docker --version
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t catnip:latest .
      - docker tag catnip:latest 785517377502.dkr.ecr.us-east-2.amazonaws.com/catnip:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 785517377502.dkr.ecr.us-east-2.amazonaws.com/catnip:latest
artifacts:
  files:
    - '**/*'
